url: "https://saeedsrd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/NoPR" # the subpath of your site, e.g. /blog
title: "کتاب ماهیت واقعیت شخصی - Nature of personal reality" # the name of your site, e.g. ACME Corp.
lang: "fa"
direction: "rtl"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: "G-KH696TBX89"

disqus:
  enable: true
  shortname: "nopr"
